rvm:
  - 1.9.3
  - 2.0.0
before_script:
  - bundle exec berks install
script:
  - bundle exec foodcritic -f any . --tags ~FC007 --tags ~FC015 --tags ~FC023
  - bundle exec rspec --color --format progress
  - bundle exec rubocop
